### ISSUE TITLE
 每一个order可以print一个invoice

### ISSUE THREAD

**Issue by peter4k** [peter4k/Foodmate#3]

**Comment by nealxyc** [comment]
01f393eb7e36b9057091391df891856d6bb4e393 can print order in simple format. Need to rearrange the format.

**Comment by nealxyc** [comment]
Latest dev app: http://foodmate-dev.parseapp.com

**Comment by nealxyc** [comment]
Updated print format in 9b7e034a58aa9b98d0e20fd24d9e4ff01acf21c8
