### ISSUE TITLE
customer版提示under construction

### ISSUE THREAD

**Issue by peter4k** [peter4k/Foodmate#32]
当用户从www.thefoodmate.com进入的时候，不显示登录界面，instead显示under construction，并且给出iphone app的链接

**Comment by nealxyc** [comment]
你用的是哪个浏览器，我试了safari， chrome，firefox和safari mobile，www.thefoodmate.com 会redirect到thefoodmate.com

**Comment by peter4k** [comment]
那个是我在aws里面跳转的

**Comment by nealxyc** [comment]
那怎么会有问题

**Comment by peter4k** [comment]
我的意思是普通用户进去的时候。。。因为我们现在只做了餐厅那边的，如果有人想通过网页点餐就得提示说还没有做好。
我想说business就从business.thefoodmate.com进去，普通用户从www.thefoodmate.com进去，如果谁进了www.thefoodmate.com就提示Under construction，顺便给个business的链接

**Comment by nealxyc** [comment]
哦，懂了。我准备把订餐的也做一下，如果来不及做好，就加个那个页面好了。

**Comment by nealxyc** [comment]
462e991cbc77032ee68fc5ad538cb4ece444e326

**Comment by nealxyc** [comment]
New index 18e4722f4e91c449bbb1c7002189ab38426da085
