### ISSUE TITLE
Used new class "OrderCourseDetai" to replace "CourseWithQuan" class

### ISSUE THREAD

**Issue by peter4k** [peter4k/Foodmate#39]
以前coursewithquan是储存在“order”下面的“courseArray”里面的。
我发现每次fetch都会产生很多个request，所以改成了一个class叫OrderCourseDetail，存了一个pointer到course，一个pointer到order，这样可以直接用一个query来fetch
以前order的“courseArray"就改成了“courseDetailArray”
哈哈哈熊哥别打我

**Comment by nealxyc** [comment]
😒😒😒😒😒

**Comment by peter4k** [comment]
算了还是不改了！太麻烦了！！我发现fetchoption的时候还是很麻烦
